### ISSUE TITLE
Expected node engine version does not exist yet?

### ISSUE THREAD

**Issue by SimonLSchlee** [exaroton/node-exaroton-api#1]
I tried `yarn add exoraton` and got:

```
error exaroton@1.1.0: The engine "node" is incompatible with this module. Expected version ">=18.0.0". Got "15.0.1"
error Found incompatible module.
```

When I look in the download section of https://nodejs.org the newest version listed as current is `15.0.1`

**Comment by matthi4s** [comment]
Hmm, no idea how that happened, should be 12, I'll fix that.

**Comment by matthi4s** [comment]
Fixed

**Comment by SimonLSchlee** [comment]
Thanks for the quick fix!
